# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - dev

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: "e114edaa-2c81-40ba-926f-d412f9af95e7"
  imageRepository: "aspnet-ah"
  containerRegistry: "ahappregistry.azurecr.io"
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
  tag: "$(Build.BuildId)"

  # Agent VM image name
  vmImageName: "ubuntu-latest"
  windowsImageName: "windows-latest"
  #aksClusterName: "AHAKSCluster"
  aksServiceConnectionName: "dev-AHAKSCluster-dev-1759080360257"
  deploymentFile: "$(Build.SourcesDirectory)/k8s/deployment.yaml"
  group: aspnet-dev
  #kubernetesNamespace: "dev"
  resourceGroupServiceConnectionName: "ah-resource-group-connection"
  keyVaultName: "aspnet-pipeline-kv"

stages:
  - stage: InitilializeKeyVault
    displayName: Initialize Key Vault Secrets
    jobs:
      - job: FetchSecrets
        displayName: Fetch FetchSecrets
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: AzureKeyVault@2
            displayName: Fetch key vault secrets
            inputs:
              azureSubscription: $(resourceGroupServiceConnectionName)
              keyVaultName: $(keyVaultName)
              SecretsFilter: "*"
              RunAsPreJob: true

  - stage: Test
    displayName: Run Tests
    dependsOn: InitilializeKeyVault
    jobs:
      - job: RunTest
        displayName: Run Tests
        pool:
          vmImage: "windows-latest"
        steps:
          - checkout: self

          - task: UseDotNet@2
            displayName: "Install .NET 8 SDK"
            inputs:
              packageType: "sdk"
              version: "8.0.x"

          - task: DotNetCoreCLI@2
            displayName: Restore packages
            inputs:
              command: "restore"
              projects: "**/*.sln"

          - task: DotNetCoreCLI@2
            displayName: Build solution
            inputs:
              command: "build"
              projects: "**/*.sln"
              arguments: "--configuration Debug --no-restore"

          - task: DotNetCoreCLI@2
            displayName: Run tests
            inputs:
              command: "test"
              projects: "AH.Tests/AH.Tests.csproj"
              arguments: "--configuration Debug --no-build --verbosity normal"
              publishTestResults: true

  - stage: Build
    displayName: Build and push stage
    dependsOn: Test
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: $(tag)
              arguments: "--build-arg ASPNETCORE_ENVIRONMENT=Production"

  - stage: DeployToDev
    displayName: Deploy to dev
    dependsOn: Build
    condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))

    jobs:
      - deployment: DeploymentToDev
        displayName: Deployment to Dev Env
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: Checkout source code

                - script: |
                    echo "Listing contents of k8s"
                    ls -l $(Build.SourcesDirectory)/k8s/
                  displayName: "List Files in k8s Directory"

                - script: |
                    sed -i 's/__TAG__/$(tag)/g' $(deploymentFile)
                  displayName: "Replace image tag in deployment file"

                - task: Kubernetes@1
                  displayName: Deploy to dev namespace in k8s
                  inputs:
                    kubernetesServiceEndpoint: $(aksServiceConnectionName)
                    namespace: dev
                    command: apply
                    arguments: "-f $(Build.SourcesDirectory)/k8s/."
